In [9]:
#create 1d array using arange function
import numpy as np
a=np.arange(51,60)
print(a)
a.size
print(a.dtype)

[51 52 53 54 55 56 57 58 59]
int64


In [10]:
#change array fro 1d array into 3d array
#use reshape function
a.shape

(9,)

In [15]:
ar=a.reshape(3,3)
ar.shape

(3, 3)

In [26]:
#create A 5*5 matrix all the values should be divisibile by 5
aar=np.arange(5,126,5)
print(aar)
print("----------Reshape array into 5*5 matrix means 5D array--------------")
ars=aar.reshape(5,5)
print(ars)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125]
Reshape array into 5*5 matrix means 5D array
[[  5  10  15  20  25]
 [ 30  35  40  45  50]
 [ 55  60  65  70  75]
 [ 80  85  90  95 100]
 [105 110 115 120 125]]


In [27]:
a1=np.arange(16).reshape(4,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
a2=np.arange(16,32).reshape(4,4)
a2

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [32]:
print("------horizontallay combine 2 matrix in one-----")
a3=np.hstack((a1,a2))
a3

------horizontallay combine 2 matrix in one-----


array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [33]:
print("------vertically  combine 2 matrix in one-----")
a4=np.vstack((a1,a2))
a4

------vertically  combine 2 matrix in one-----


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])